apiVersion: apps/v1
kind: Deployment
metadata:
  name: vuejs
  labels:
    app: vuejs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vuejs
  template:
    metadata:
      labels:
        app: vuejs
    spec:
      securityContext:
        fsGroup: 2000 
      containers:
      - name: vuejs
        image: taillanm/dockerize-vuejs-app
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80